apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountlookupservice
  labels:
    app: accountlookupservice
    app.kubernetes.io/name: accountlookupservice
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # exeed the replicas by 1 pod
  selector:
    matchLabels:
      app: accountlookupservice
  template:
    metadata:
      labels:
        app: accountlookupservice
    spec:
      containers:
      - name: account-lookup-service
        image: mojaloop/account-lookup-service:v10.3.0.2-pisp
        livenessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /health
            port: 4001
        readinessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /health
            port: 4001
        env:
          - name: ALS_SWITCH_ENDPOINT
            value: http://centralledger:3001
          - name: ALS_DATABASE__HOST
            value: mysql-als
---
apiVersion: v1
kind: Service
metadata:
  name: accountlookupservice
spec:
  ports:
  - port: 4001
  selector:
    app: accountlookupservice
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: accountlookupserviceadmin
spec:
  ports:
  - port: 4002
  selector:
    app: accountlookupservice
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: accountlookupservice
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths: 
          - path: /account-lookup-service(/|$)(.*)
            backend:
              serviceName: accountlookupservice
              servicePort: 4001
          - path: /account-lookup-service-admin(/|$)(.*)
            backend:
              serviceName: accountlookupserviceadmin
              servicePort: 4002