apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionrequestsservice
  labels:
    app: transactionrequestsservice
    app.kubernetes.io/name: transactionrequestsservice

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # exeed the replicas by 1 pod
  selector:
    matchLabels:
      app: transactionrequestsservice
  template:
    metadata:
      labels:
        app: transactionrequestsservice
    spec:
      containers:
      - name: transaction-requests-service
        image: mojaloop/transaction-requests-service:v10.6.1.1-pisp
        livenessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /health
            port: 4003
        readinessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /health
            port: 4003
        env:
          - name: ES_SWITCH_ENDPOINT
            value: http://centralledger:3001
         
---
apiVersion: v1
kind: Service
metadata:
  name: transactionrequestsservice
spec:
  ports:
  - port: 4003
  selector:
    app: transactionrequestsservice
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: transactionrequestsservice
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths: 
          - path: /transaction-requests-service(/|$)(.*)
            backend:
              serviceName: transactionrequestsservice
              servicePort: 4003