version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  central-ledger:
    image: mojaloop/central-ledger:v10.3.1.2-pisp
    container_name: central-ledger
    command: sh -c "/opt/central-ledger/wait4/wait4.js central-ledger && node src/api/index.js"
    ports:
      - "3001:3001"
    volumes:
       - ./docker/central-ledger/default.json:/opt/central-ledger/config/default.json
       - ./docker/wait4:/opt/central-ledger/wait4
    environment:
      - LOG_LEVEL=info
      - CLEDG_SIDECAR__DISABLED=true
      - CLEDG_MONGODB__DISABLED=false
    networks:
      - mojaloop-net
    depends_on:
      - mysql
      - kafka
      - objstore
    healthcheck:
      test: wget -q http://172.17.0.1:3001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    extra_hosts:
      - "moja-simulator.local:172.17.0.1"
      - "simulator:172.17.0.1"
      - "host.docker.internal:172.17.0.1"
      - "simulator.local:172.17.0.1"

  objstore:
    image: mongo:latest
    container_name: objstore
    # Disable logging, this container is not that important and rather verbose
    logging:
      driver: none
    ports:
      - "27017:27017"
    networks:
      - mojaloop-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  quoting-service:
    image: "mojaloop/quoting-service:v10.1.0"
    container_name: quoting-service
    networks:
      - mojaloop-net
    depends_on:
      - mysql
    ports:
      - "3002:3002"
    volumes:
      - ./docker/quoting-service/default.json:/opt/quoting-service/config/default.json
    healthcheck:
      test: wget -q http://172.17.0.1:3002/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    extra_hosts:
      - "moja-simulator.local:172.17.0.1"
      - "simulator:172.17.0.1"
      - "host.docker.internal:172.17.0.1"
      - "simulator.local:172.17.0.1"

  ml-api-adapter:
    image: mojaloop/ml-api-adapter:v10.3.1.2-pisp
    container_name: ml-api-adapter
    command: sh -c "/opt/ml-api-adapter/wait4/wait4.js ml-api-adapter && node src/api/index.js"
    ports:
      - "3000:3000"
    volumes:
      - ./docker/ml-api-adapter/default.json:/opt/ml-api-adapter/config/default.json
      - ./docker/wait4:/opt/ml-api-adapter/wait4
    environment:
      - LOG_LEVEL=info
    networks:
      - mojaloop-net
    depends_on:
      - kafka
    healthcheck:
      test: wget -q http://172.17.0.1:3000/health -O /dev/null || exit 1
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 30s
    extra_hosts:
      - "central-ledger.local:172.17.0.1"
      - "central-ledger:172.17.0.1"
      - "simulator:172.17.0.1"
      - "moja-simulator.local:172.17.0.1"
      - "host.docker.internal:172.17.0.1"
      - "simulator.local:172.17.0.1"

  mysql:
    image: mysql/mysql-server
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      # Note: this fixes the permissions issue, but docker-compose up will fail on first attempt
      - ./docker/sql-init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=${DBUSER:-central_ledger}
      - MYSQL_PASSWORD=${DBPASS:-password}
      - MYSQL_DATABASE=${DBUSER:-central_ledger}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - mojaloop-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s

  simulator:
    image: mojaloop/simulator:v9.5.0
    container_name: simulator
    ports:
      - "8444:8444"
    environment:
      - LOG_LEVEL=info
      - TRANSFERS_ENDPOINT=http://ml-api-adapter:3000
      - QUOTES_ENDPOINT=http://quoting-service:3002
      - PARTIES_ENDPOINT=http://account-lookup-service:4002
      - TRANSACTION_REQUESTS_ENDPOINT=http://transaction-request-service:4003
      - TRANSFERS_FULFIL_RESPONSE_DISABLED=false
    networks:
      - mojaloop-net
    healthcheck:
      test: wget -q http://172.17.0.1:8444/health -O /dev/null || exit 1
      timeout: 20s
      retries: 10
      interval: 30s
    extra_hosts:
      - "central-ledger.local:172.17.0.1"
      - "central-settlement.local:172.17.0.1"
      - "ml-api-adapter.local:172.17.0.1"
      - "account-lookup-service.local:172.17.0.1"
      - "account-lookup-service-admin.local:172.17.0.1"
      - "quoting-service.local:172.17.0.1"
      - "moja-simulator.local:172.17.0.1"
      - "central-ledger:172.17.0.1"
      - "central-settlement:172.17.0.1"
      - "ml-api-adapter:172.17.0.1"
      - "account-lookup-service:172.17.0.1"
      - "account-lookup-service-admin:172.17.0.1"
      - "quoting-service:172.17.0.1"
      - "simulator:172.17.0.1"
      - "host.docker.internal:172.17.0.1"
      - "simulator.local:172.17.0.1"
      - "transaction-request-service:172.17.0.1"

  transaction-requests-service:
    image: mojaloop/transaction-requests-service:v10.4.0.0-pisp
    container_name: transaction-requests-service
    ports:
      - "4003:4003"
    volumes:
      - ./docker/transaction-requests-service/default.json:/opt/transaction-requests-service/config/default.json
    networks:
      - mojaloop-net
    healthcheck:
      test: wget -q http://172.17.0.1:4003/health -O /dev/null || exit 1
      timeout: 20s
      retries: 10
      interval: 30s
    extra_hosts:
      - "central-ledger.local:172.17.0.1"
      - "central-settlement.local:172.17.0.1"
      - "ml-api-adapter.local:172.17.0.1"
      - "account-lookup-service.local:172.17.0.1"
      - "account-lookup-service-admin.local:172.17.0.1"
      - "quoting-service.local:172.17.0.1"
      - "moja-simulator.local:172.17.0.1"
      - "central-ledger:172.17.0.1"
      - "central-settlement:172.17.0.1"
      - "ml-api-adapter:172.17.0.1"
      - "account-lookup-service:172.17.0.1"
      - "account-lookup-service-admin:172.17.0.1"
      - "quoting-service:172.17.0.1"
      - "simulator:172.17.0.1"
      - "host.docker.internal:172.17.0.1"
      - "simulator.local:172.17.0.1"

  kafka:
    image: johnnypark/kafka-zookeeper:2.3.0
    container_name: kafka
    volumes:
      - ./docker/kafka/:/opt/kafka_2.12-2.3.0/config/
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - ZOO_LOG4J_PROP=WARN
    networks:
      - mojaloop-net
    healthcheck:
      test: ["CMD" ,"/opt/kafka_2.12-2.3.0/bin/kafka-broker-api-versions.sh","--bootstrap-server","172.17.0.1:9092"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s

  central-settlement:
    image: mojaloop/central-settlement:v9.5.0
    container_name: central-settlement
    command: sh -c "/opt/central-settlement/wait4/wait4.js central-settlement && node src/api/index.js"
    networks:
      - mojaloop-net
    depends_on:
      - mysql
      - kafka
    ports:
      - "3007:3007"
    volumes:
       - ./docker/central-settlement/default.json:/opt/central-settlement/config/default.json
       - ./docker/wait4:/opt/central-settlement/wait4

  account-lookup-service:
    image: mojaloop/account-lookup-service:v10.3.0.2-pisp
    container_name: account-lookup-service
    command: sh -c "/opt/account-lookup-service/wait4/wait4.js account-lookup-service && npm run migrate && node src/index.js server"
    ports:
      - "4001:4001"
      - "4002:4002"
    environment:
      - LOG_LEVEL=info
      - ALS_DISPLAY_ROUTES=false
    networks:
      - mojaloop-net
    depends_on:
      - mysql-als
      - central-ledger
    volumes:
      - ./docker/account-lookup-service/default.json:/opt/account-lookup-service/config/default.json
      - ./docker/wait4:/opt/account-lookup-service/wait4
    healthcheck:
      test: wget -q http://172.17.0.1:4001/health -O /dev/null || exit 1
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s
    extra_hosts:
      - "moja-simulator.local:172.17.0.1"
      - "simulator:172.17.0.1"
      - "host.docker.internal:172.17.0.1"
      - "simulator.local:172.17.0.1"
      - "transaction-request-service:172.17.0.1"

  mysql-als:
    image: mysql/mysql-server
    container_name: mysql_als
    ports:
      - "3306:3306"
    volumes:
      - ./docker/sql-als-init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=${DBUSER:-account_lookup}
      - MYSQL_PASSWORD=${DBPASS:-password}
      - MYSQL_DATABASE=${DBUSER:-account_lookup}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - mojaloop-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql-als"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 30s

  ## DFSP A
  dfspa-backend:
    image: "mojaloop/mojaloop-simulator:v9.4.1.1-pisp"
    container_name: dfspa-backend
    env_file: ./dfsp_a/dfsp_a_backend.env
    volumes:
       - ./dfsp_a/rules.json:/src/rules.json
    ports:
      - "9000:3000"
      - "9002:3002"
      - "9003:3003"
    extra_hosts:
      - "dfspa-scheme-adapter:172.17.0.1"

  dfspa-scheme-adapter:
    image: "mojaloop/sdk-scheme-adapter:v9.4.11.1-pisp"
    container_name: dsfpa-scheme-adapter
    env_file: ./dfsp_a/dfsp_a_scheme_adapter.env
    volumes:
      - "./dfsp_a/secrets:/secrets"
      - "./dfsp_a/jwsVerificationKeys:/jwsVerificationKeys"
    ports:
      - "5000:4000"
      - "5002:4001"
    networks:
      - mojaloop-net
    depends_on:
      - dfspa-redis
    restart: always
    extra_hosts:
      - "central-ledger.local:172.17.0.1"
      - "central-settlement.local:172.17.0.1"
      - "ml-api-adapter.local:172.17.0.1"
      - "account-lookup-service.local:172.17.0.1"
      - "account-lookup-service-admin.local:172.17.0.1"
      - "quoting-service.local:172.17.0.1"
      - "moja-simulator.local:172.17.0.1"
      - "central-ledger:172.17.0.1"
      - "central-settlement:172.17.0.1"
      - "ml-api-adapter:172.17.0.1"
      - "account-lookup-service:172.17.0.1"
      - "account-lookup-service-admin:172.17.0.1"
      - "quoting-service:172.17.0.1"
      - "simulator:172.17.0.1"
      - "host.docker.internal:172.17.0.1"
      - "simulator.local:172.17.0.1"
      - "transaction-request-service:172.17.0.1"
      - "dfspa-backend:172.17.0.1"

  dfspa-redis:
    container_name: dfspa-redis
    image: "redis:5.0.4-alpine"
    networks:
      - mojaloop-net
    restart: always

  ## DFSP B
  dfspb-backend:
    image: "mojaloop/mojaloop-simulator:v9.4.1.1-pisp"
    container_name: dfspb-backend
    env_file: ./dfsp_b/dfsp_b_backend.env
    volumes:
       - ./dfsp_b/rules.json:/src/rules.json
    ports:
      - "10000:3000"
      - "10002:3002"
      - "10003:3003"
    extra_hosts:
      - "dfspb-scheme-adapter:172.17.0.1"

  dfspb-scheme-adapter:
    image: "mojaloop/sdk-scheme-adapter:v9.4.11.1-pisp"
    container_name: dfspb-scheme-adapter
    env_file: ./dfsp_b/dfsp_b_scheme_adapter.env
    volumes:
      - "./dfsp_b/secrets:/secrets"
      - "./dfsp_b/jwsVerificationKeys:/jwsVerificationKeys"
    ports:
      - "6000:4000"
      - "6002:4001"
    networks:
      - mojaloop-net
    depends_on:
      - dfspb-redis
    restart: always
    extra_hosts:
      - "central-ledger.local:172.17.0.1"
      - "central-settlement.local:172.17.0.1"
      - "ml-api-adapter.local:172.17.0.1"
      - "account-lookup-service.local:172.17.0.1"
      - "account-lookup-service-admin.local:172.17.0.1"
      - "quoting-service.local:172.17.0.1"
      - "moja-simulator.local:172.17.0.1"
      - "central-ledger:172.17.0.1"
      - "central-settlement:172.17.0.1"
      - "ml-api-adapter:172.17.0.1"
      - "account-lookup-service:172.17.0.1"
      - "account-lookup-service-admin:172.17.0.1"
      - "quoting-service:172.17.0.1"
      - "simulator:172.17.0.1"
      - "host.docker.internal:172.17.0.1"
      - "simulator.local:172.17.0.1"
      - "transaction-request-service:172.17.0.1"
      - "dfspb-backend:172.17.0.1"

  dfspb-redis:
    container_name: dfspb-redis
    image: "redis:5.0.4-alpine"
    networks:
      - mojaloop-net
    restart: always

 ## PISP
  pisp-backend:
    image: "mojaloop/mojaloop-simulator:v9.4.1.1-pisp"
    container_name: pisp-backend
    env_file: ./pisp/pisp_backend.env
    ports:
      - "11000:3000"
      - "11002:3002"
      - "11003:3003"
    extra_hosts:
      - "pisp-scheme-adapter:172.17.0.1"

  pisp-scheme-adapter:
    image: "mojaloop/sdk-scheme-adapter:v9.4.11.1-pisp"
    container_name: pisp-scheme-adapter
    env_file: ./pisp/pisp_scheme_adapter.env
    volumes:
      - "./pisp/secrets:/secrets"
      - "./pisp/jwsVerificationKeys:/jwsVerificationKeys"
    ports:
      - "7000:4000"
      - "7002:4001"
    networks:
      - mojaloop-net
    depends_on:
      - pisp-redis
    restart: always
    extra_hosts:
      - "central-ledger.local:172.17.0.1"
      - "central-settlement.local:172.17.0.1"
      - "ml-api-adapter.local:172.17.0.1"
      - "account-lookup-service.local:172.17.0.1"
      - "account-lookup-service-admin.local:172.17.0.1"
      - "quoting-service.local:172.17.0.1"
      - "moja-simulator.local:172.17.0.1"
      - "central-ledger:172.17.0.1"
      - "central-settlement:172.17.0.1"
      - "ml-api-adapter:172.17.0.1"
      - "account-lookup-service:172.17.0.1"
      - "account-lookup-service-admin:172.17.0.1"
      - "quoting-service:172.17.0.1"
      - "simulator:172.17.0.1"
      - "host.docker.internal:172.17.0.1"
      - "simulator.local:172.17.0.1"
      - "transaction-request-service:172.17.0.1"
      - "pisp-backend:172.17.0.1"

  pisp-thirdparty-api-adapter:
    image: "mojaloop/thirdparty-api-adapter:v10.4.2"
    container_name: pisp-thirdparty-api-adapter
    command: sh -c "/opt/thirdparty-api-adapter/wait4/wait4.js thirdparty-api-adapter && npm run start"
    ports:
      - "12000:3008"
    volumes:
       - ./docker/thirdparty-api-adapter/default.json:/opt/thirdparty-api-adapter/config/default.json
       - ./docker/wait4:/opt/thirdparty-api-adapter/wait4
    networks:
      - mojaloop-net
    depends_on:
      - kafka
    healthcheck:
      test: wget -q http://172.17.0.1:12000/health -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
    extra_hosts:
      - "central-ledger.local:172.17.0.1"
      - "central-settlement.local:172.17.0.1"
      - "ml-api-adapter.local:172.17.0.1"
      - "account-lookup-service.local:172.17.0.1"
      - "account-lookup-service-admin.local:172.17.0.1"
      - "quoting-service.local:172.17.0.1"
      - "moja-simulator.local:172.17.0.1"
      - "central-ledger:172.17.0.1"
      - "central-settlement:172.17.0.1"
      - "ml-api-adapter:172.17.0.1"
      - "account-lookup-service:172.17.0.1"
      - "account-lookup-service-admin:172.17.0.1"
      - "quoting-service:172.17.0.1"
      - "simulator:172.17.0.1"
      - "host.docker.internal:172.17.0.1"
      - "simulator.local:172.17.0.1"
      - "transaction-request-service:172.17.0.1"
      - "pisp-backend:172.17.0.1"

  pisp-redis:
    container_name: pisp-redis
    image: "redis:5.0.4-alpine"
    networks:
      - mojaloop-net
    restart: always
